package com.example.persistence.domain;

import java.io.Serializable;

public class Car implements Serializable {
    /**
     *  ,所属表字段为car.id
     */
    private Long id;

    /**
     *  品牌id,所属表字段为car.brand_id
     */
    private Integer brandId;

    /**
     *  库存数量,所属表字段为car.inventory
     */
    private Integer inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table car
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.brand_id
     *
     * @return the value of car.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.brand_id
     *
     * @param brandId the value for car.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.inventory
     *
     * @return the value of car.inventory
     *
     * @mbggenerated
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.inventory
     *
     * @param inventory the value for car.inventory
     *
     * @mbggenerated
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }
}